input.onButtonPressed(Button.A, function () {
    pins.digitalWritePin(DigitalPin.P4, 1)
    for (let index = 0; index < 4; index++) {
        pins.servoWritePin(AnalogPin.P13, 135)
        pins.servoWritePin(AnalogPin.P8, 45)
        basic.pause(100)
        pins.servoWritePin(AnalogPin.P13, 30)
        pins.servoWritePin(AnalogPin.P8, 30)
    }
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P13, 80)
    pins.servoWritePin(AnalogPin.P8, 100)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
    basic.pause(200)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
})
input.onButtonPressed(Button.B, function () {
    for (let index = 0; index < 4; index++) {
        pins.servoWritePin(AnalogPin.P13, 135)
        pins.servoWritePin(AnalogPin.P8, 45)
        basic.pause(100)
        pins.servoWritePin(AnalogPin.P13, 30)
        pins.servoWritePin(AnalogPin.P8, 30)
    }
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
    pins.servoWritePin(AnalogPin.P13, 80)
    pins.servoWritePin(AnalogPin.P8, 100)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
    basic.pause(200)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P4, 1)
})
