input.onButtonPressed(Button.A, function () {
    pins.digitalWritePin(DigitalPin.P4, 1)
    for (let index = 0; index < 4; index++) {
        pins.servoWritePin(AnalogPin.P13, 135)
        pins.servoWritePin(AnalogPin.P8, 45)
        basic.pause(100)
        pins.servoWritePin(AnalogPin.P13, 30)
        pins.servoWritePin(AnalogPin.P8, 30)
    }
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(100)
    pins.servoWritePin(AnalogPin.P13, 180)
    pins.servoWritePin(AnalogPin.P8, 180)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(100)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(100)
})
